### ISSUE TITLE
Length is undefined

### ISSUE THREAD

**Issue by jimmykane** [digitalBush/jquery.maskedinput#290]
Hi there, 

in this function

```
function androidInputEvent() {
                    var curVal = input.val(), pos = input.caret();
                    if (curVal.length < oldVal.length) {
                        for (checkVal(!0); pos.begin > 0 && !tests[pos.begin - 1]; ) pos.begin--;
                        if (0 === pos.begin) for (;pos.begin < firstNonMaskPos && !tests[pos.begin]; ) pos.begin++;
                        input.caret(pos.begin, pos.begin);
                    } else {
                        for (checkVal(!0); pos.begin < len && !tests[pos.begin]; ) pos.begin++;
                        input.caret(pos.begin, pos.begin);
                    }
                    tryFireCompleted();
                }
```

the oldVal.length is undefined. What's the case with this ? 

Shouldn't the oldVal be checked for existing length before? Bad code here

**Comment by digitalBush** [comment]
Something is definitely weird here. `oldVal` gets set in the keydown event which I'm sure is broken on android.

**Comment by jimmykane** [comment]
Yes a simple check for now does it for me but I think the general concept should be fixed. 

patch with something like this I think is enough for now. 

```
function androidInputEvent() {
                    var curVal = input.val(), pos = input.caret();
                    if (oldVal && oldVal.length && curVal.length < oldVal.length) {
                        for (checkVal(!0); pos.begin > 0 && !tests[pos.begin - 1]; ) pos.begin--;
                        if (0 === pos.begin) for (;pos.begin < firstNonMaskPos && !tests[pos.begin]; ) pos.begin++;
                        input.caret(pos.begin, pos.begin);
                    } else {
                        for (checkVal(!0); pos.begin < len && !tests[pos.begin]; ) pos.begin++;
                        input.caret(pos.begin, pos.begin);
                    }
                    tryFireCompleted();
                }
```

Should I make a pull request?

**Comment by digitalBush** [comment]
@jimmykane When does the error happen for you? Are you even seeing keydown event?

**Comment by jimmykane** [comment]
@digitalBush  I have the library running on production on high traffic campaigns. Had this error a log from a lot of Samsung devices. Happens on more of 10% and that means that the keydown event in these browsers is broken or does not fire. In that case the check did the trick but I haven't digged that much into your code to see the consequences.

**Comment by digitalBush** [comment]
@jimmykane thanks for reporting back. If you don't mind, submit a pull request and I'll get this in there.
