### ISSUE TITLE
non-jQuery version

### ISSUE THREAD

**Issue by TrySound** [digitalBush/jquery.maskedinput#292]
Your plugin isn't so strongly depend from jQuery.
I like VanillaJS plugins. We can make such version.
What do you think?

**Comment by grabus** [comment]
It would be great!

**Comment by digitalBush** [comment]
I've toyed with the idea, but I think there will be some hidden extra work there. jQuery does some event normalization across browsers that we would have to overcome. At this time it's just not something I'm terribly interested in.

**Comment by TrySound** [comment]
Okey. I will start own project inspired by this.
