### ISSUE TITLE
dinamically change mask

### ISSUE THREAD

**Issue by sirg2003** [digitalBush/jquery.maskedinput#297]
Hello. I have input (for phone) like that: 
$("#phone").mask("+9 (999) 999-99-99");
but i need option to dinamically change mask. How can i do if user print 11 symbols then using this mask:
mask("+9 (999) 999-99-99");
but if user prints 12 symbols then mask changing to such mask:
mask("+9 (9999) 999-99-99");

**Comment by gandarez** [comment]
+1

**Comment by digitalBush** [comment]
You can register your own keypress handlers and remask with your new pattern when you see the sequence you are expecting.
