### ISSUE TITLE
Don't allow invalid dates.

### ISSUE THREAD

**Issue by franciscocorrales** [digitalBush/jquery.maskedinput#299]
When a date is set, like: 

`.mask("99/99/9999",{placeholder:"mm/dd/yyyy"});`

The user can input something like: 13/32/3000, which is not a valid date. Other invalid dates: 02/29/2015

It would be great, that the max date would be: 12/31/xxxx.

**Comment by markvantilburg** [comment]
It's more masking than validating. It would allow only numeric values but not validate them. Maybe you can incorporate a validating framework to check the actual date. Might be an option to write your own mask, as this mask just states enter "2 numbers 1 slash 2 numbers 1 slash and 4 numbers"

**Comment by franciscocorrales** [comment]
yeah, you're right...
But adding two frameworks doesn't seem elegant to me. Maybe people will drop using this plugin and go for jQuery UI or something..
It would be nice that this plugin, had some validation in it.

**Comment by RQuadling** [comment]
Can the masks be regex based? But that alone (unless you want to go ninja on the regex) is going to be a toughee. Mixing minimal, expected validations (and dates are pretty much the one most people would want to be validated) would be a good option. Maybe as a jquery.maskedinput.validation plugins?

http://www.regular-expressions.info/dates.html gives a good walk through for date validation.

**Comment by markvantilburg** [comment]
I run it in combination with validity https://github.com/whatgoodisaroad/validity

**Comment by digitalBush** [comment]
At the moment there are no plans to build in validation support into this library since there are plenty of validation libraries out there already.
