### ISSUE TITLE
Regex can only be one character

### ISSUE THREAD

**Issue by tomprats** [digitalBush/jquery.maskedinput#301]
When trying to mask something like a username field, it's pretty terrible just doing what's below to allow 3 to 7 character usernames

    $mask.definitions["!"] = "^[a-z0-9_-]$"
    $("#username").mask("!!!?!?!?!?!?!?!?!", { placeholder: "" })

I see the limitations that can be caused by having to display the placeholder, but It'd be really cool to have a "repeat x times" argument

**Comment by digitalBush** [comment]
This library isn't really designed to do what you are trying to do with it. This is only meant to assist with fixed width inputs.
