### ISSUE TITLE
should I use the dist or src folder for using the latest src JS file?

### ISSUE THREAD

**Issue by armyofda12mnkeys** [digitalBush/jquery.maskedinput#304]
Hey,
Curious why isn't the 'source' file in the distribution folder not matching the file in the src folder?
https://raw.githubusercontent.com/digitalBush/jquery.maskedinput/master/src/jquery.maskedinput.js
https://raw.githubusercontent.com/digitalBush/jquery.maskedinput/master/dist/jquery.maskedinput.js

Which one is the more updated that the dist/jquery.maskedinput.min.js is based off of? ... 
I was using the dist/jquery.maskedinput.min.js but then needed to debug, so wasn't sure which src file to use since I saw a stackoverflow reference saying the src/ has the latest as the website http://digitalbush.com/projects/masked-input-plugin/ isn't updated with most latest file.

**Comment by armyofda12mnkeys** [comment]
Doh, I may have jumped the gun. realized the dist file looks like it might be the src file that ran through a minifier that only got rid of extra spaces and comments probably. Can you confirm?

**Comment by digitalBush** [comment]
Use the `dist` folder. At some point we may split up the src into multiple files.
