### ISSUE TITLE
Location of the cursor at click on input

### ISSUE THREAD

**Issue by PLavrynenko** [digitalBush/jquery.maskedinput#306]
When the user clicks on the INPUT cursor doesn't turn beginning of the line.
![screenshot_1](https://cloud.githubusercontent.com/assets/6515827/7250042/92e422fc-e827-11e4-81b7-d5bd1a091d82.png)
```
jQuery("#partner_modules_admin_models_CommissionFixed_price").mask("9?999999",{'placeholder':' '});
```

**Comment by gandarez** [comment]
+1

**Comment by digitalBush** [comment]
Closing this one to track on #307 since it has a few more details of the different click behaviors.

**Comment by jt3k** [comment]
+1
