### ISSUE TITLE
"Delete" Key press Issue with Alphanumeric Masking

### ISSUE THREAD

**Issue by raghunathsanam** [digitalBush/jquery.maskedinput#311]
Hi,
I am using something like .mask("aa99999"). Entered gk12345.

Issue 1: Delete 'g' and tabout or click any place outside text box. I see only k in the input field.

Issue 2: Start deleting the value starting from 'g'. Will be able to delete only 'gk' after that i am not able to delete.

http://jsfiddle.net/Raghunadh/7de4cLow/

Chrome Version 40.0.2214.111 m
Windows 7 Enterprise

**Comment by raghunathsanam** [comment]
Hi,
   Will this be considered for the next release?

**Comment by digitalBush** [comment]
I'm not able to reproduce the first one, but #2 is definitely a bug.

**Comment by digitalBush** [comment]
Actually, spoke too soon. The second behavior is by design. 'a' means that one an alpha character can fit. When we try to backspace the numbers get "stuck" because they can't fit in the alpha slot. If those first two characters are alphanumeric [example](http://jsfiddle.net/digitalbush/7de4cLow/1/), then it works.

**Comment by raghunathsanam** [comment]
Hi,
      Thanks for the reply.  I can't use alphanum for the first 2 places.  It should be only alpha.  Please don't close the defect as it is a valid one.

**Comment by digitalBush** [comment]
@raghunathsanam I wasn't able to reproduce anything on your first problem. I did notice that your jsfiddle was using a very old version of jQuery and my plugin. I've updated to the latest version [in this example](http://jsfiddle.net/digitalbush/7de4cLow/5/). Does that behave any different?

**Comment by raghunathsanam** [comment]
I can still see the Issue 1 even with the latest jQuery and maskedinput plugin link given above.
