### ISSUE TITLE
How do I get the raw value?

### ISSUE THREAD

**Issue by migig** [digitalBush/jquery.maskedinput#318]
Before sending a form to the server, we want to remove the mask.

e.g.
a date mask is `"99/99/9999"`
so let's say value will be `"01/01/2015"`

How do I transform that to `"01012015"`? Is the value typed by the user saved somewhere?

**Comment by FagnerMartinsBrack** [comment]
Try

```
$( ... ).mask( "unmask" ).val();
```

**Comment by migig** [comment]
@FagnerMartinsBrack I appreciate your help. For me though that just changes the mask to `"unmask"` and then returns `""`.

**Comment by FagnerMartinsBrack** [comment]
Oh ok, try retrieving the data form the input:

```javascript
$( input ).data( $.mask.dataName ); // raw mask
```

**Comment by migig** [comment]
@FagnerMartinsBrack 

Hope I'm doing it right, but that doesn't work for me?

For example, this:
````javascript
$(".foo").mask("99/99/9999", { completed: function () {
  console.log("Unmasked value is: " + (this).data($.mask.dataName)); }
  });
````

Then I get this:
````javascript
Unmasked value is: function () {
                    return $.map(buffer, function(c, i) {
                        return tests[i] && c != getPlaceholder(i) ? c : null;
                    }).join("");
                }
````

**Comment by migig** [comment]
*I hope I'm wrong* (I've gone into the source, but it's unfamiliar to me), but I'm beginning to think that the raw value isn't saved? Can anyone confirm this?

If this is true, it would make a great addition to the library.

Often you want to guide the user when inputting data. But you want the raw value sent to the server for processing and storage.

**Comment by FagnerMartinsBrack** [comment]
It sets the data [here](https://github.com/digitalBush/jquery.maskedinput/blob/24c3bfaec10c043b408f4f2bc94e5926c0059927/src/jquery.maskedinput.js#L375-L379). If it stores a data information that returns a function then try to execute it:

```javascript
$( input ).data( $.mask.dataName )(); // raw mask
```

As you can see, everything I am telling you here I am not checking the code execution, it is just a fast code inspection.

Also, this is internal behavior. Be aware that, ideally, a feature does not exist unless it is documented, and retrieving the raw value doesn't seems to be documented in the `README.md`.

**Comment by migig** [comment]
@FagnerMartinsBrack 

Ok that works!

I agree with you though, and if it isn't documented, then I can't use it. I'm going to make a feature request (to update the docs) for this separately.

Thanks for your help.

**Comment by rosaAdl** [comment]
I used:
```javascript
$( input ).data().mask.getCleanVal(),
```
and it worked for me.

**Comment by desyncr** [comment]
This worked for me:

```js
$(element).data().rawMaskFn
```

Plugin version 1.0.
