### ISSUE TITLE
Add "@" in custom mask definitions

### ISSUE THREAD

**Issue by gianku** [digitalBush/jquery.maskedinput#325]
I'd like to know if there's a way for add char @ in custom mask definitions. I'm using WordPress and Ninja Forms (Masked input Plugin is included), in my custom file.js I added this code:

`jQuery(document).ready(function(){
jQuery.mask.definitions['x'] = "[-A-Za-z0-9_\.@]";
jQuery("#ninja_forms_field_2").mask("xxxxxxxxx?xxxxxxxxxxxxxxxxxxxxxxxxx");
});`

My field works fine when I digit letters from A(a) to Z(z), numbers from 0 to 9 and these chars (- _ and . ) but when I digit @, this char disappears soon after, Why ?

**Comment by digitalBush** [comment]
I know this is late, but I'm not able to reproduce this issue.
