### ISSUE TITLE
1.4.1 is not on nuget

### ISSUE THREAD

**Issue by markvantilburg** [digitalBush/jquery.maskedinput#334]
https://www.nuget.org/packages/jQuery.MaskedInput/

Displays old version

**Comment by FagnerMartinsBrack** [comment]
Ping @stimms?

**Comment by stimms** [comment]
Oh hey, I was not paying attention at all to new releases of this. I'll put it on my list for this week.

**Comment by stimms** [comment]
Updated. I don't seem to have right to mark this as complete.

**Comment by digitalBush** [comment]
Thanks @stimms!
