### ISSUE TITLE
How to listen to input

### ISSUE THREAD

**Issue by ogonkov** [digitalBush/jquery.maskedinput#344]
I've tired to look through docs and code, but couldn't figure out how to listen to `<input>` changing?

For example, i've got some listener on parent element, that listen to propagated `input` event. But with `maskedinput` this is not possible, because it prevents default action on keypress.

How to keep `maskedinput` functionality and don't break my own listeners?

**Comment by avalanche1** [comment]
This doesn't work.because of https://github.com/digitalBush/jquery.maskedinput/blob/master/dist/jquery.maskedinput.js#L127
Use keyup or keydown events.

**Comment by ogonkov** [comment]
Sad.
