### ISSUE TITLE
Cursor in FF won't change position when using keyboard

### ISSUE THREAD

**Issue by falcon397** [digitalBush/jquery.maskedinput#352]
So I tested this on your demo page as well, but in Firefox 44.0.1 (current version as of writing this) when I input data into a field and attempt to move the cursor using the left or right arrows, or home or end keys, the cursor doesn't move.  I can however use the mouse to adjust the cursor position.  Keyboard/cursor functionality seems to work fine in Chrome and IE 10, but for whatever reason FF seems to hate the keyboard/cursor relationships on masked fields.  I normally wouldn't be bothered reporting most issues, but cursor movement using the keyboard is a pretty big issue for most users.

**Comment by kaljak** [comment]
This was already reported in #275 
This pull request should fix the issue: #348

**Comment by falcon397** [comment]
That pull request 348 does not address the issue, when applied, if you put a space in the text box it places the cursor at the beginning of the text box and adds new input to the beginning of the text string.  Although the arrows do work, it is not really a good fix, but I'll close the issue due to it being already brought up.
