### ISSUE TITLE
Can set a mask format: +375 xx xxx xx xx xxxxxx 

### ISSUE THREAD

**Issue by bear-wolf** [digitalBush/jquery.maskedinput#357]
I use this plugin. It is cool, but I have set a mask next format : +375 xx xxx xx xx xxxxxx (x - 15 count)
I know that this format not exist. 
Can set this mask used this plugin?
Terms next: 
                   I need use this format ;
                   or
                   I need a format number with less count 'x' characters

Thank you.

**Comment by luiscoms** [comment]
Did you try this?

    $("#input-id").mask("+375 99 999 99 99 999999");

**Comment by bear-wolf** [comment]
This correct example, but if a user has phone for example:
 +375 99 999
that this code will be not correct and system not miss him.
I want use 1 variant & two variant.

**Comment by luiscoms** [comment]
You could use

    $("#input-id").mask("+375 99 999? 99 99 999999");

So, all mask after the `?` character is optional

**Comment by bear-wolf** [comment]
Everything is fine now.
Thankyou very much.
