### ISSUE TITLE
How to prevent shifting after blur event?

### ISSUE THREAD

**Issue by AOnurOzcan** [digitalBush/jquery.maskedinput#359]
Hello. I really need help.
For example. There is a mask  
```javascript
$("input[name=ctlKata]").mask("*****", {autoclear: false});
```
The input is like this : _ _ _ _ _ 
If I write some data like -> _ 2 _ 3 _ 
Then when I try to enter data to next input, previous input is shifting. 
I mean, it turns to -> 2 3 _ _ _

I hope, I could tell. How can I prevent this? Thank you.

**Comment by digitalBush** [comment]
@AOnurOzcan Sorry, but this is the built in behavior.
